"""create upload_batch and lansia_record

Revision ID: 34929417a200
Revises: 
Create Date: 2026-05-31 15:37:10.722017

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34929417a200'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_batch',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('bulan', sa.String(length=30), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('total_desa', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('stats_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lansia_record',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('desa', sa.String(length=100), nullable=False),
    sa.Column('nama', sa.String(length=150), nullable=False),
    sa.Column('nik', sa.String(length=20), nullable=True),
    sa.Column('umur', sa.Float(), nullable=True),
    sa.Column('jenis_kelamin', sa.Float(), nullable=True),
    sa.Column('kunjungan_baru', sa.Float(), nullable=True),
    sa.Column('kunjungan_lama', sa.Float(), nullable=True),
    sa.Column('bb', sa.Float(), nullable=True),
    sa.Column('tb', sa.Float(), nullable=True),
    sa.Column('imt', sa.Float(), nullable=True),
    sa.Column('td_sistolik', sa.Float(), nullable=True),
    sa.Column('td_diastolik', sa.Float(), nullable=True),
    sa.Column('td_kategori', sa.String(length=5), nullable=True),
    sa.Column('hb_N', sa.Float(), nullable=True),
    sa.Column('hb_K', sa.Float(), nullable=True),
    sa.Column('hb', sa.Float(), nullable=True),
    sa.Column('kolesterol_N', sa.Float(), nullable=True),
    sa.Column('kolesterol_T', sa.Float(), nullable=True),
    sa.Column('kolesterol', sa.Float(), nullable=True),
    sa.Column('gula_darah_N', sa.Float(), nullable=True),
    sa.Column('gula_darah_T', sa.Float(), nullable=True),
    sa.Column('gula_darah', sa.Float(), nullable=True),
    sa.Column('asam_urat_N', sa.Float(), nullable=True),
    sa.Column('asam_urat_T', sa.Float(), nullable=True),
    sa.Column('asam_urat', sa.Float(), nullable=True),
    sa.Column('kemandirian_A', sa.Float(), nullable=True),
    sa.Column('kemandirian_B_ringan', sa.Float(), nullable=True),
    sa.Column('kemandirian_B_sedang', sa.Float(), nullable=True),
    sa.Column('kemandirian_C_berat', sa.Float(), nullable=True),
    sa.Column('kemandirian_total', sa.Float(), nullable=True),
    sa.Column('level_kemandirian', sa.Integer(), nullable=True),
    sa.Column('skilas_kognitif', sa.Float(), nullable=True),
    sa.Column('skilas_mobilitas', sa.Float(), nullable=True),
    sa.Column('skilas_malnutrisi', sa.Float(), nullable=True),
    sa.Column('skilas_penglihatan', sa.Float(), nullable=True),
    sa.Column('skilas_pendengaran', sa.Float(), nullable=True),
    sa.Column('skilas_depresi', sa.Float(), nullable=True),
    sa.Column('gangguan_paru', sa.Float(), nullable=True),
    sa.Column('gangguan_ginjal', sa.Float(), nullable=True),
    sa.Column('gangguan_kognitif', sa.Float(), nullable=True),
    sa.Column('gangguan_penglihatan', sa.Float(), nullable=True),
    sa.Column('gangguan_pendengaran', sa.Float(), nullable=True),
    sa.Column('penurunan_kognitif', sa.Float(), nullable=True),
    sa.Column('keterbatasan_mobilitas', sa.Float(), nullable=True),
    sa.Column('malnutrisi', sa.Float(), nullable=True),
    sa.Column('gejala_depresi', sa.Float(), nullable=True),
    sa.Column('pengobatan_diobati', sa.Float(), nullable=True),
    sa.Column('pengobatan_dirujuk', sa.Float(), nullable=True),
    sa.Column('konseling_B', sa.Float(), nullable=True),
    sa.Column('konseling_L', sa.Float(), nullable=True),
    sa.Column('konseling_S', sa.Float(), nullable=True),
    sa.Column('penyuluhan', sa.Float(), nullable=True),
    sa.Column('pemberdayaan_lansia', sa.Float(), nullable=True),
    sa.Column('is_outlier', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['upload_batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('lansia_record', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lansia_record_batch_id'), ['batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_lansia_record_desa'), ['desa'], unique=False)
        batch_op.create_index(batch_op.f('ix_lansia_record_nik'), ['nik'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lansia_record', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lansia_record_nik'))
        batch_op.drop_index(batch_op.f('ix_lansia_record_desa'))
        batch_op.drop_index(batch_op.f('ix_lansia_record_batch_id'))

    op.drop_table('lansia_record')
    op.drop_table('upload_batch')
    # ### end Alembic commands ###
